# Site settings
title: Dewdrop Games
email: contact@dewdropgames.com
url: https://www.google.com/+DewdropgamesStudio
description: "A micro team of ambitious and adventurous video game craftsmasters. Though you may call us arists, suit yourself."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0b0c1e #darkblue
  secondary: a05550 #crimson
  secondary-dark: 4797bc #blue

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: google-plus
    url: https://www.google.com/+DewdropgamesStudio
  - title: facebook
    url: https://www.facebook.com/pages/Dewdrop-Games/1611114062499160
  - title: vk
    url: http://vk.com/dewdropgames
  - title: github
    url: https://github.com/DewdropGamesStudio

# Postal address (add as many lines as necessary)
address:
  - line: Mira av. 20 42
  - line: 141196 Fryazino
  - line: Moscow region, Russia

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
